import turtle

obj = turtle.Turtle()
obj.speed(100)

def draw(l):
    if(l<2):
        return
    else:
        obj.left(60)
        obj.forward(l)
        draw(l/4)
        obj.backward(l)
        obj.right(30)
        obj.forward(l)
        draw(l/4)
        obj.backward(l)
        obj.right(30)
        obj.forward(l)
        draw(l/4)
        obj.backward(l)
        obj.right(30)
        obj.forward(l)
        draw(l/4)
        obj.backward(l)
        obj.right(30)
        obj.forward(l)
        draw(l/4)
        obj.backward(l)
        obj.right(30)
        obj.forward(l)
        draw(l/4)
        obj.backward(l)
        obj.right(30)
        obj.forward(l)
        draw(l/4)
        obj.backward(l)
        obj.right(30)
        obj.forward(l)
        draw(l/4)
        obj.backward(l)
        obj.right(30)
        obj.forward(l)
        draw(l/4)
        obj.backward(l)
        obj.right(30)
        obj.forward(l)
        draw(l/4)
        obj.backward(l)
        obj.right(30)
        obj.forward(l)
        draw(l/4)
        obj.backward(l)
        obj.right(30)
        obj.forward(l)
        draw(l/4)
        obj.backward(l)
        obj.right(90)



draw(300)
input()