import turtle

obj = turtle.Turtle()
obj.speed(100)
# obj.backward(300)
# obj.left(90)
# obj.backward(300)
# obj.right(90)
obj.clear()

def draw(l):
    if(l < 3.7):
        return
    else:
        if l > 11:
            obj.up()
            draw(l / 3)
            obj.up()
            obj.forward(l)
            obj.left(60)
            obj.up()
            draw(l / 3)
            obj.up()
            obj.forward(l)
            obj.right(120)
            obj.up()
            draw(l / 3)
            obj.up()
            obj.forward(l)
            obj.left(60)
            obj.up()
            draw(l / 3)
            obj.up()
            obj.forward(l)
            obj.up()
            obj.backward(l)
            obj.right(60)
            obj.up()
            obj.backward(l)
            obj.left(120)
            obj.up()
            obj.backward(l)
            obj.right(60)
            obj.up()
            obj.backward(l)
        else:
            obj.down()
            draw(l / 3)
            obj.forward(l)
            obj.left(60)
            draw(l / 3)
            obj.forward(l)
            obj.right(120)
            draw(l / 3)
            obj.forward(l)
            obj.left(60)
            draw(l / 3)
            obj.forward(l)
            obj.backward(l)
            obj.right(60)
            obj.backward(l)
            obj.left(120)
            obj.backward(l)
            obj.right(60)
            obj.backward(l)
l=150
for i in range(3):
    obj.right(120)
    draw(l)
    obj.forward(l*3)

input()